//! Golden-frame regression tests (Renderer V2, ADR 0014).
//!
//! Render the flat-illustration goose at fixed poses — both views, both facings, and a
//! deterministic mid-stride — and compare against committed PNGs. This catches visual
//! regressions in the rig geometry, the view state machine, or the painter that the
//! numeric pinning tests would miss.
//!
//! The goldens were generated by this same code (clean-room renderer), so they should
//! match exactly on a given machine; a small per-channel tolerance + mismatch budget
//! guards against incidental anti-aliasing noise. To regenerate after an intentional,
//! reviewed visual change, set `HONK_BLESS=1` and re-run. Missing files always fail.

use honk_engine::math::Vec2;
use honk_engine::render::render_centered;
use honk_engine::rig::{Rig, RigAnim, RigInput};
use honk_engine::time::DT;
use honk_engine::tiny_skia::Pixmap;
use std::path::{Path, PathBuf};

const SIZE: u32 = 180;
/// Per-channel absolute difference tolerated before a pixel counts as "changed".
const CHANNEL_TOL: i32 = 16;
/// Fraction of pixels allowed to exceed the tolerance.
const MAX_BAD_FRACTION: f64 = 0.001;

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("golden")
        .join(format!("{name}.png"))
}

fn compare(name: &str, rig: &Rig) {
    let rendered = render_centered(SIZE, SIZE, rig).expect("pixmap allocation");
    let path = golden_path(name);
    let bless = std::env::var_os("HONK_BLESS").is_some();
    require_committed_golden(&path).unwrap_or_else(|message| panic!("{message}"));

    if bless {
        rendered.save_png(&path).expect("write golden png");
        eprintln!("golden '{name}' written to {}", path.display());
        return;
    }

    let golden = Pixmap::load_png(&path).expect("load golden png");
    assert_eq!(
        (golden.width(), golden.height()),
        (rendered.width(), rendered.height()),
        "golden '{name}' has different dimensions"
    );

    let (a, b) = (golden.data(), rendered.data());
    assert_eq!(a.len(), b.len(), "golden '{name}' byte length mismatch");

    let bad = a
        .chunks_exact(4)
        .zip(b.chunks_exact(4))
        .filter(|(ga, gb)| {
            ga.iter()
                .zip(gb.iter())
                .any(|(&x, &y)| (x as i32 - y as i32).abs() > CHANNEL_TOL)
        })
        .count();

    let total = (SIZE * SIZE) as f64;
    let fraction = bad as f64 / total;
    assert!(
        fraction <= MAX_BAD_FRACTION,
        "golden '{name}' drifted: {bad} px ({:.2}%) exceed tolerance (budget {:.2}%)",
        fraction * 100.0,
        MAX_BAD_FRACTION * 100.0
    );
}

fn require_committed_golden(path: &Path) -> Result<(), String> {
    path.exists()
        .then_some(())
        .ok_or_else(|| format!("missing committed golden: {}", path.display()))
}

#[test]
fn missing_goldens_fail_instead_of_being_created() {
    let path = golden_path("this-golden-must-never-exist");
    assert!(require_committed_golden(&path).is_err());
    assert!(!path.exists());
}

const AT: Vec2 = Vec2 { x: 300.0, y: 300.0 };

/// Deterministic mini-simulation: tick the animation state along a straight walk.
fn walk(anim: &mut RigAnim, start: Vec2, dir_deg: f32, speed: f32, neck: f32, secs: f32) -> Rig {
    let velocity = Vec2::from_angle_degrees(dir_deg) * speed;
    let ticks = (secs / DT).round().max(1.0) as usize;
    let mut center = start;
    let mut now = 0.0_f64;
    let mut rig = None;
    for _ in 0..ticks {
        now += DT as f64;
        center = center + velocity * DT;
        rig = Some(
            anim.update(&RigInput {
                center,
                direction_deg: dir_deg,
                neck_target: neck,
                speed,
                velocity,
                step_time: 0.2,
                now,
                dt: DT,
            })
            .primary,
        );
    }
    rig.expect("at least one tick")
}

#[test]
fn golden_side_rest() {
    // Standing tall at the idle posture, facing right.
    compare("side_rest", &Rig::update(AT, 0.0, 0.45, 0.0));
}

#[test]
fn golden_side_reaching() {
    // Neck fully raised/reaching.
    compare("side_reaching", &Rig::update(AT, 0.0, 1.0, 0.0));
}

#[test]
fn golden_side_left() {
    // Mirror correctness: same stance, facing left.
    compare("side_left", &Rig::update(AT, 180.0, 0.45, 0.0));
}

#[test]
fn golden_side_mid_stride() {
    // Deterministic walk: one foot planted, one mid-swing.
    let mut anim = RigAnim::new(AT, 0.0);
    let rig = walk(&mut anim, AT, 0.0, 80.0, 0.55, 0.63);
    compare("side_mid_stride", &rig);
}

#[test]
fn golden_top_down() {
    // Steep dive engages the top-down view (fade completed well before sampling).
    let mut anim = RigAnim::new(AT, 0.0);
    walk(&mut anim, AT, 0.0, 80.0, 0.45, 0.2);
    let rig = walk(&mut anim, AT, 90.0, 120.0, 0.55, 0.8);
    compare("top_down", &rig);
}

#[test]
fn golden_top_down_diag() {
    // Top-down rotates freely: a diagonal heading.
    let mut anim = RigAnim::new(AT, 0.0);
    walk(&mut anim, AT, 0.0, 80.0, 0.45, 0.2);
    let rig = walk(&mut anim, AT, 315.0, 120.0, 0.55, 0.8);
    compare("top_down_diag", &rig);
}
