//! Golden-frame regression tests.
//!
//! Render the procedural goose at a few fixed poses to an offscreen pixmap and compare
//! against committed PNGs. This catches visual regressions in the rig geometry or the
//! renderer that the numeric pinning tests would miss.
//!
//! The goldens were generated by this same code (clean-room renderer), so they should
//! match exactly on a given machine; a small per-channel tolerance + mismatch budget
//! guards against incidental anti-aliasing noise. To regenerate after an intentional
//! visual change, delete `tests/golden/*.png` (or set `HONK_BLESS=1`) and re-run.

use honk_engine::math::Vec2;
use honk_engine::render::render_centered;
use honk_engine::rig::Rig;
use honk_engine::tiny_skia::Pixmap;
use std::path::PathBuf;

const SIZE: u32 = 160;
/// Per-channel absolute difference tolerated before a pixel counts as "changed".
const CHANNEL_TOL: i32 = 16;
/// Fraction of pixels allowed to exceed the tolerance.
const MAX_BAD_FRACTION: f64 = 0.01;

fn golden_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("golden")
        .join(format!("{name}.png"))
}

fn compare(name: &str, rig: &Rig) {
    let rendered = render_centered(SIZE, SIZE, rig).expect("pixmap allocation");
    let path = golden_path(name);
    let bless = std::env::var_os("HONK_BLESS").is_some();

    if bless || !path.exists() {
        std::fs::create_dir_all(path.parent().unwrap()).expect("create golden dir");
        rendered.save_png(&path).expect("write golden png");
        eprintln!("golden '{name}' written to {}", path.display());
        return;
    }

    let golden = Pixmap::load_png(&path).expect("load golden png");
    assert_eq!(
        (golden.width(), golden.height()),
        (rendered.width(), rendered.height()),
        "golden '{name}' has different dimensions"
    );

    let (a, b) = (golden.data(), rendered.data());
    assert_eq!(a.len(), b.len(), "golden '{name}' byte length mismatch");

    let bad = a
        .chunks_exact(4)
        .zip(b.chunks_exact(4))
        .filter(|(ga, gb)| {
            ga.iter()
                .zip(gb.iter())
                .any(|(&x, &y)| (x as i32 - y as i32).abs() > CHANNEL_TOL)
        })
        .count();

    let total = (SIZE * SIZE) as f64;
    let fraction = bad as f64 / total;
    assert!(
        fraction <= MAX_BAD_FRACTION,
        "golden '{name}' drifted: {bad} px ({:.2}%) exceed tolerance (budget {:.2}%)",
        fraction * 100.0,
        MAX_BAD_FRACTION * 100.0
    );
}

#[test]
fn golden_rest_pose() {
    // Default goose: at (300,300), facing 90° (+y), neck raised.
    compare("rest", &Rig::default());
}

#[test]
fn golden_extended_neck() {
    compare("extended", &Rig::update(Vec2::new(300.0, 300.0), 90.0, 1.0));
}

#[test]
fn golden_facing_right() {
    // Facing 0° (+x), neck partially extended.
    compare(
        "facing_right",
        &Rig::update(Vec2::new(300.0, 300.0), 0.0, 0.3),
    );
}
