"""Compile the reviewed leaf SVG masters into bounded Rust paths and palette variants."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'Assets' / 'Leaves'
NAMES = ('maple', 'oak', 'birch', 'ginkgo')
NUMBER = r'[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?'
TOKEN = re.compile(r'[MLCZ]|' + NUMBER)


def path_commands(data: str) -> list[tuple[str, list[float]]]:
    if re.sub(r'[\s,]', '', TOKEN.sub('', data)):
        raise ValueError('Leaf masters must use explicit absolute M/L/C/Z commands')
    tokens = TOKEN.findall(data)
    commands = []
    i = 0
    while i < len(tokens):
        command = tokens[i]
        count = {'M': 2, 'L': 2, 'C': 6, 'Z': 0}[command]
        values = list(map(float, tokens[i + 1:i + 1 + count]))
        if len(values) != count or any(abs(value) > 10.001 for value in values):
            raise ValueError('Leaf geometry exceeds its twenty-pixel control bounds')
        commands.append((command, values))
        i += 1 + count
    if not commands or commands[0][0] != 'M' or commands[-1][0] != 'Z':
        raise ValueError('Leaf paths must contain a closed silhouette')
    return commands


def outputs() -> dict[Path, str]:
    palette = json.loads((ART / 'palette.json').read_text(encoding='utf-8'))
    if list(palette) != ['gold', 'orange', 'red', 'brown']:
        raise ValueError('The four palette roles must keep their existing ordering')
    generated = ['// @generated by script/build_leaf_art.py from Assets/Leaves/masters/.',
                 '// Review the source SVGs; do not edit generated paths.',
                 'use tiny_skia::{Path, PathBuilder};', '',
                 'pub(super) const PALETTE: [(u8, u8, u8); 4] =']
    colors = []
    for rgb in palette.values():
        if len(rgb) != 3 or any(not isinstance(c, int) or not 0 <= c <= 255 for c in rgb):
            raise ValueError('Invalid leaf color')
        colors.append('(' + ', '.join(str(c) for c in rgb) + ')')
    generated += ['    [' + ', '.join(colors) + '];', '', 'pub(super) fn paths() -> [[Path; 2]; 4] {',
                  '    [maple(), oak(), birch(), ginkgo()]', '}', '']
    result = {}
    for name in NAMES:
        source = (ART / 'masters' / f'{name}.svg').read_text(encoding='utf-8')
        svg = ET.fromstring(source)
        if svg.attrib != {'viewBox': '-12 -12 24 24'}:
            raise ValueError('Unexpected leaf SVG viewport or attributes')
        elements = list(svg)
        if [e.tag.rsplit('}', 1)[-1] for e in elements] != ['title', 'path', 'path']:
            raise ValueError('Leaf SVG masters must contain only a title and two paths')
        if [e.attrib.get('data-tone') for e in elements[1:]] != ['blade', 'veins']:
            raise ValueError('Missing leaf color roles')
        generated += [f'fn {name}() -> [Path; 2] {{', '    [']
        for element in elements[1:]:
            if set(element.attrib) != {'data-tone', 'fill', 'd'}:
                raise ValueError('Unexpected SVG path attribute')
            generated += ['        {', '            let mut p = PathBuilder::new();']
            for command, values in path_commands(element.attrib['d']):
                method = {'M': 'move_to', 'L': 'line_to', 'C': 'cubic_to', 'Z': 'close'}[command]
                numbers = ', '.join(f'{v:.4f}' for v in values)
                generated.append(f'            p.{method}({numbers});')
            generated += ['            p.finish().expect("validated leaf SVG path")', '        },']
        generated += ['    ]', '}', '']
        for color, rgb in palette.items():
            dark = tuple(max(0, c - offset) for c, offset in zip(rgb, (38, 28, 12)))
            recolored = source.replace('fill="#e2b835"', 'fill="#%02x%02x%02x"' % tuple(rgb))
            recolored = recolored.replace('fill="#bc9c29"', 'fill="#%02x%02x%02x"' % dark)
            result[ART / f'{name}-{color}.svg'] = recolored
    result[ROOT / 'crates/honk-engine/src/render/leaf_art.rs'] = '\n'.join(generated)
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Leaf asset drift: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    print('Leaf artwork: four masters, sixteen recolors and cached Rust geometry agree')


if __name__ == '__main__':
    main()
